### ISSUE TITLE
Program window opens very small

### ISSUE THREAD

**Issue by lineber** [CryoByte33/steam-deck-utilities#27] opened 2023-02-20 09:23 UTC
While connected to the docking station, the program window is the size of an icon.  It is impossible to read.

I've changed resolution to match the steam deck and it persists. I've mirror the steamdeck and it persists.

My monitor is a 1080p.

**Comment by CryoByte33** [comment] 2023-02-20 11:45
The latest version should have a fix as @ajite mentioned, please let us know!

**Comment by lineber** [comment] 2023-02-20 20:58
I started using the tool this morning, but I ran the update tool right now, and the issue still persists. However, I can drag the program window to the deck screen and read it, as now it is correct size only on the deck screen.

**Comment by lineber** [comment] 2023-02-20 21:03
![Screenshot_20230220_155956](https://user-images.githubusercontent.com/2454244/220198092-af096c62-56c6-4660-80c8-f42e57d4c0a4.png)

**Comment by Xilufer** [comment] 2023-02-20 21:09
Just wanted to comment that I just ran the update and I'm experiencing the same issue. Additionally, if you open the app undocked and then plug in an external display the window resizes from very large to very small several times before settling on very small.

**Comment by lineber** [comment] 2023-02-20 21:28
Please merge with https://github.com/CryoByte33/steam-deck-utilities/pull/25 it appears to be a similar issue. Although, all my buttons are working.

**Comment by ajite** [comment] 2023-02-21 00:52
Yes. It looks like the same issue. The button glitch happens when moving it from one screen to another. Happened to me during testing. I think it’s when you go from small to normal.

**Comment by CryoByte33** [comment] 2023-02-21 03:41
#25 has been merged for quite a while, this is actually a duplicate of #28. Closing here.

**Closed by CryoByte33** 2023-02-21 03:41 UTC
