### ISSUE TITLE
Tiny GUI on external monitor

### ISSUE THREAD

**Issue by Cyntaelis** [CryoByte33/steam-deck-utilities#28] opened 2023-02-20 09:53 UTC
The gui is unusably small on my external monitors, though it can be fixed by dragging the window onto the steam deck's internal screen, where it resizes itself. That said it won't let me resize manually and goes back to being tiny when moved back to the external monitor. I'm assuming it sets the size based on the monitor it's on? 

A picture of how it looks like, and my monitor setup:
![cryo issue](https://user-images.githubusercontent.com/67953493/220061045-58dcb195-9651-4240-91ad-ba386cdb0d17.png)

Currently using the official dock and here are the [changes I've done with pacman](https://gist.github.com/Cyntaelis/5cc33cdaa24c8d6e6be9b94fa20ddff7)

This gui issue happened with both an upgraded prior install and a fresh install.

**Comment by ajite** [comment] 2023-02-20 11:30
It seems like a duplicate of #25 . Can you update and try again see if you still have the issue?

**Comment by Cyntaelis** [comment] 2023-02-20 12:17
Issue persists on both update and reinstall. Haven't checked the detailed commit timestamps but I believe I first started updating to 2.0 after c4db8d2bef0c2ac87ee53cd0c2bd8f00164f1602 was out.

**Comment by ajite** [comment] 2023-02-20 13:09
Can you send the output of:

`cat /home/deck/.cryo_utilities/launcher.sh`

And can you try to run directly from the terminal see if that fixes it:

`FYNE_SCALE=1 /home/deck/.cryo_utilities/launcher.sh`

**Comment by Cyntaelis** [comment] 2023-02-20 14:47
```
(deck@steamdeck ~)$ cat /home/deck/.cryo_utilities/launcher.sh
!/bin/bash
if [ "$(xrandr --current | grep '*' | xargs | cut -d ' ' -f1)" = "800x1280" ]; then
  export FYNE_SCALE=0.25
fi

"$HOME"/.cryo_utilities/cryo_utilities gui
```

Running it from term with FYNE_SCALE=0.25 doesn't fix the problem, but running it without that var makes it scale properly on both of my external monitors, though it completely disappears when dragged to my steam deck monitor. I'm not exactly sure where it goes, and I have to right click on the taskbar icon to drag it back to the external monitors, where it returns to normal.

I believe the issue is that `xrandr --current | grep '*' | xargs | cut -d ' ' -f1` always returns `800x1280` if the steam deck monitor is in use regardless of if there are external monitors or not. 

For reference, my `xrandr --current` looks like https://gist.github.com/Cyntaelis/b5e33cfd99fbb8f879c01a204343717f

My shell isn't great but maybe looking for multiple `*` could be a good way to check for other monitors, though I find that a lot of apps including this don't respect the xrandr primary flag and show up on monitor 2 instead of 3. For me isn't an issue but I don't know how much of a problem this would be on other setups.

**Comment by CryoByte33** [comment] 2023-02-20 14:54
Ah, that was actually a PR from this morning (#25) . I tested it, but it seems like that slipped through the cracks. 

Unfortunately, because Fyne needs the scaling factor set when booting, there's not a simple way for it to realize which monitor it should size for, and changing scaling can only happen on program startup. I'm not sure of a way to make it work when both screens are connected, other than maybe just assuming it should always be scaled for the "last" monitor?

Of course, that brings the problem of setting the external to primary while still using the internal too 🤔

Any thoughts on the issue? I guess that I could make a zenity popup that allows the user to choose the scaling, but that seems pretty irritating.

**Comment by ajite** [comment] 2023-02-20 15:53
I think it's the steamdeck orientation that makes it not working with a scale of 1.

Instead of looking for `800x1280` we can check the name of the primary display. It seems to me that the steamdeck screen's name is `eDP` while external screens are using `DisplayPort-X`

But you still have an issue when using the deck screen as a primary display when opening the app on an external display.

```
if [ "$(xrandr | grep 'primary'  | cut -d ' ' -f1)" = "eDP" ]; then
  export FYNE_SCALE=0.25
fi
```

**Comment by CryoByte33** [comment] 2023-02-20 15:56
> I think it's the steamdeck orientation that makes it not working with a scale of 1.
This is exactly it, and it's my largest problem with Fyne. Unfortunately, I found it pretty late in development 😓

>Instead of looking for 800x1280 we can check the name of the primary display. It seems to me that the steamdeck screen's name is eDP while external screens are using DisplayPort-X

Good catch! Maybe we could count the screens, if there's one, check if it's the deck screen. If there's 2, then assume a scale of 1?

**Comment by ajite** [comment] 2023-02-20 16:22
> Maybe we could count the screens, if there's one, check if it's the deck screen. If there's 2, then assume a scale of 1?

We could do that as well. The thing is that it will look too big when the steam deck is set as the primary display.
I think it would be okay since they can just drag the window to their other monitor. Too big is better than too small.

**Comment by CryoByte33** [comment] 2023-02-20 16:24
Alright, I think that's probably our best bet then. I don't have time to update it at the moment, but will try to in the coming days. Sorry for the issue everyone!

**Comment by ajite** [comment] 2023-02-20 16:28
#37 should do it. I will try some more tomorrow morning.

**Comment by carteakey** [comment] 2023-02-20 17:34
I can confirm, #37 fixed the issue for me when connected to external monitors.

**Comment by CryoByte33** [comment] 2023-02-20 17:36
Great to hear, I'll try it out in the morning!

**Comment by carteakey** [comment] 2023-02-20 20:24
ok, so #37 has an issue, the new `grep 'connected'` always returns 2, even if the external monitor is dis**connected**, so running the app without any external monitor does not work properly.

```bash
(deck@steamdeck ~)$ xrandr
Screen 0: minimum 320 x 200, current 1280 x 800, maximum 16384 x 16384
eDP connected primary 1280x800+0+0 right (normal left inverted right x axis y axis) 60mm x 60mm
   800x1280      60.00*+
   800x600       60.00  
   640x480       60.00  
DisplayPort-0 disconnected (normal left inverted right x axis y axis)
```

**Comment by CryoByte33** [comment] 2023-02-21 03:40
I can't check at the moment, but does `xdpyinfo | grep dimension | wc -l` return 2 when connected to an external display? I originally had xdpyinfo in launcher, but #25 swapped it out since it "correctly" specified the resolution.

**Comment by CryoByte33** [comment] 2023-02-21 04:30
Looks like #37 just updated, can anyone confirm that it works properly?

**Comment by ajite** [comment] 2023-02-21 04:33
>  but does xdpyinfo | grep dimension | wc -l return 2 when connected to an external display?

Not on my deck.

> Looks like https://github.com/CryoByte33/steam-deck-utilities/pull/37 just updated, can anyone confirm that it works properly?

I added a space in the grep to avoid getting disconnected device. That's why it was always returning 2.

A long term solution would be to make it work with Fyne without having to manually set the environment variable.

**Comment by CryoByte33** [comment] 2023-02-21 04:37
> A long term solution would be to make it work with Fyne without having to manually set the environment variable.

Fyne is very opinionated about scaling, so dynamic seems to be out of the question. We should probably open an issue with them to get vertical resolutions properly accounted for, though.

**Comment by CryoByte33** [comment] 2023-02-21 18:28
I just confirmed as well, the code is merged 🙂

> The only minor caveat seems to be that i can't move the app between screens, which might be resolved by your planned long term solutions.

I'm not sure if there's anything we can do about this for now, but if I think about something I'll open an enhancement issue.

I'll close this for now as #37 was merged. Please reopen if the issue isn't resolved!

**Closed by CryoByte33** 2023-02-21 18:28 UTC

**Comment by scuffe82** [comment] 2023-02-23 00:56
Hi, I just tested with latest on a fully patched stable steamos. The window was massive and not useable on a deck undocked. I rebooted without anything connected to double check and it was the same result. In reading through the issues i manually adjusted the FYNE_SCALE to .3 and was able to use the app on the deck screen. If you would like any logs or output please let me know and i'll grab them for you.

**Comment by ajite** [comment] 2023-02-23 05:28
Can you share your  `xrandr` output ?

**Comment by CryoByte33** [comment] 2023-02-23 05:29
@scuffe82 just to confirm, you ran the tool using the desktop icon or the launcher.sh, correct?

**Comment by mkikets99** [comment] 2023-03-13 12:42
Hey everyone. Got latest version on Anbernic Win600 with holo-iso 4.0 (SteamOS 3.4)...
As a result - tiny window...
![image](https://user-images.githubusercontent.com/22869811/224704386-c05b5759-8a2d-4a50-9ca1-e734064f29b1.png)

xrandr output:
```bash
(mkikets@holoiso Desktop)$ xrandr
Screen 0: minimum 320 x 200, current 1280 x 720, maximum 16384 x 16384
eDP connected primary 1280x720+0+0 right (normal left inverted right x axis y axis) 720mm x 1280mm
   720x1280      60.05*+
   640x480       60.05  
HDMI-A-0 disconnected (normal left inverted right x axis y axis)
DisplayPort-0 disconnected (normal left inverted right x axis y axis)
```
