### ISSUE TITLE
Installing on a new SD card causes issues

### ISSUE THREAD

**Issue by lukedds** [CryoByte33/steam-deck-utilities#62] opened 2023-02-23 10:16 UTC
Not sure there's anything you can do about this one, but it's an issue I came across.

I had a game installed on an SD card, used CryoUtilities to move the compdata onto the card. Decided I didn't want to use that card anymore, so I uninstalled it from that card and installed it to another card via steam.

I should have thought about this before reinstalling it, but of course the symlink was never removed but now pointed towards a location where the data didn't exist. Steam never complained about this and installed the game anyway. Then of course it failed to launch when the compdata it tried to access came up blank.

I'd already formatted the old card so the old compdata was gone, thus had to unlink and reinstall the game, which I think is the only way to fix that?

Guessing there's not much you can do about this but I'm sure other people will have come across it.

**Comment by CryoByte33** [comment] 2023-02-23 10:19
There's not much you can do at this moment, but I'm working on an option to move all synced data back to the internal drive.

As for the symlinks, simply use the cleanup tool and delete all data for any affected games, it'll purge the symlinks and allow the Deck to recreate them as usual 🙂

**Comment by lukedds** [comment] 2023-02-23 10:24
The cleanup tool didn't pick the game up, but I'm guessing that might be because I'd already formatted the card. Is there a way to get the tool to pick the symlinks up and purge them even when the data for the game no longer exists on the SD card? Keeping a record on the deck of created symlinks or something?

**Comment by CryoByte33** [comment] 2023-02-23 10:28
I want to keep the tool stateless, but I just found a bug that's causing it to not pick up symlinks. I'm looking at it now 🙂

**Comment by lukedds** [comment] 2023-02-23 10:29
Yeah, fair enough keeping it stateless. Thanks for looking and thanks for your work

**Comment by CryoByte33** [comment] 2023-02-23 10:51
This should be fixed with #63 , try updating and seeing if the issue is resolved please!

**Comment by lukedds** [comment] 2023-02-23 10:55
I manually removed the symlinks but will attempt to recreate and retest at some point.

Just looked at #63, this potentially an edge case but it it worth checking that the symlink is a CryoUtilities symlink and not one created by someone/something else?

**Comment by CryoByte33** [comment] 2023-02-23 10:59
I'm not sure if there would be a case when someone would need that, as it already poses the question of which to delete, right? I might not understand, but it seems to me like the intent is to be able to delete _any_ shader/compat data/symlinks 🤔

**Comment by lukedds** [comment] 2023-02-23 11:03
I might be misunderstanding the code, but it looks like it currently appends all symlinks to folderList regardless of whether CryoUtils created them or not. I just wondered if that could lead to unintended consequences. Thinking it through I'm guessing not because the user will still have to manually choose to delete, so I can probably close this issue :shipit:

**Comment by CryoByte33** [comment] 2023-02-23 11:28
It does get all symlinks, but even if they aren't from CU, you still may want to delete them. Yeah, I'll close for now.

Please reopen this if the issue persists or you have a similar issue!

**Closed by CryoByte33** 2023-02-23 11:28 UTC
Labels: bug
