### ISSUE TITLE
[Enhancement] Ability to run on all Linux distributions

### ISSUE THREAD

**Issue by coreybruce** [CryoByte33/steam-deck-utilities#85] opened 2023-02-26 03:19 UTC
Hey it would be awesome if this tool was available for all Linux distros so they can use these game enhancing options. I would been keen to test and try it.

**Comment by CryoByte33** [comment] 2023-02-26 08:00
This is already planned, but I should have made an issue for it. #65 is already pending testing, and is the only thing that should really prevent this.

I'm moving this weekend so I won't be able to test/merge it today, but hopefully this week 🙂

**Comment by coreybruce** [comment] 2023-02-26 08:35
Oh awesome to here, keep me updated because I would love to be a tester

**Comment by brandonbeaumia** [comment] 2023-02-27 01:17
I'd love to test this as well! I've watched this issue; let us know  when a branch is ready and I'll give it a shot.

**Comment by CryoByte33** [comment] 2023-02-28 07:49
@koloved This is pending #65 's merge. I still have to go through all of them to test and merge, but I've been supremely busy with moving the past few days.

**Comment by CryoByte33** [comment] 2023-03-02 09:40
@brandonbeaumia @coreybruce the update is live, please try the latest version of CU on your Linux systems and let me know if there are any issues!

**Comment by coreybruce** [comment] 2023-03-02 09:43
Awesome I'll try it out soon 😁👌

**Comment by coreybruce** [comment] 2023-03-02 12:04
So I tried the latest binary

```
2023/03/02 21:49:19 open /home/corey/.cryo_utilities/cryoutilities.log: no such file or directory
panic: open /home/corey/.cryo_utilities/cryoutilities.log: no such file or directory

goroutine 1 [running, locked to thread]:
log.Panic({0xc000237eb0?, 0x2d?, 0x42?})
	/opt/hostedtoolcache/go/1.20.1/x64/src/log/log.go:384 +0x65
main.main()
	/home/runner/work/steam-deck-utilities/steam-deck-utilities/cmd/cryoutilities/main.go:21 +0xb1
```

**Comment by CryoByte33** [comment] 2023-03-02 12:31
Yeah, you'd need to use the installer. There's another improvement to be made about having the binary create the files on its own, but it's "supposed" to be in that directory already, so this shouldn't be seen.

**Comment by coreybruce** [comment] 2023-03-02 13:00
Ahh right I see :smile:

**Comment by brandonbeaumia** [comment] 2023-03-02 23:10
Ran the installer but I can't see well enough to test anything out! Should I open a separate issue for this?:

1080p on Pop!_OS 22.04.

![Tiny CU](https://user-images.githubusercontent.com/650565/222582671-f851e314-e18f-4715-8eaa-5d218302f6c8.png)

**Comment by koloved** [comment] 2023-03-02 23:26
Test it on Arch , applied all settings expert swap, 
i have 64 gb swap partition , app said Unknown size

on 1080p its have usual size

**Comment by brandonbeaumia** [comment] 2023-03-03 00:45
> i manually download .sh file then install

Same here, forgot to mention that part.

**Comment by CryoByte33** [comment] 2023-03-03 09:45
> Swap Size was showing as unknown (no swap on this install by default!). I was unable to change the size in the interface. After creating and setting a swapfile manually it doesn't report the size or allow changes either.

To clarify, you have a swap file and it's shown by `swapon -s`?  The tool only supports swap files, not partitions.

**Comment by brandonbeaumia** [comment] 2023-03-03 19:55
My apologies, I think I figured it out. `swapon -s` always returned nothing so I created a swapfile, confirmed it showed up, added it to fstab, and then restarted and opened CU only to get the same problem. I did not notice the cryptswap in my fstab file, and after commenting out the cryptswap my recently made swapfile is persisting. When I use the swapfile, CU reports correctly.

Regarding swappiness: this value also didn't persist past reboot and I failed to notice until now.

Pop apparently uses a custom script to initialize ZRAM at startup (https://github.com/pop-os/default-settings/pull/163), which includes setting swappiness.  Setting swappiness in Sysctl.conf doesn't do anything, I think because the ZRAM script overwrites that value. I know ZRAM can do great things for memory management, but I do wonder if the swappiness values apply in the same way when this feature is enabled...

Is general Linux compatibility something that you have as an ultimate goal, even? I can't tell if perhaps this was just low-hanging fruit that made it an option for some tinkerers to try out on other systems. There are apparently a lot of difference between distros, as I've found out trying to get this working on Pop. If that's a goal, I can start opening relevant issues and do more deep-dive testing and maybe even learn a little Go in the process! But if you'd rather not open that can of worms, I totally understand. Maybe it's something to consider further in the future, or just safeguard against unsupported configurations for now.

Issues that I _could_ open (and look into some more) if they are relevant to the project goals:

- Launcher.sh sets incorrect scale (would research more to figure out why this happens on my system specifically)
- Swappiness value doesn't persist on Pop!_OS
- Swapfiles supported but swap partitions are not
- VRAM instructions are irrelevant for non-Deck devices

**Comment by CryoByte33** [comment] 2023-03-03 20:11
> Setting swappiness in Sysctl.conf doesn't do anything

This is actually set with tmpfiles.d, as are the rest of the tweaks.

> Is general Linux compatibility something that you have as an ultimate goal, even? I can't tell if perhaps this was just low-hanging fruit that made it an option for some tinkerers to try out on other systems.

Honestly, the primary use case and end goal for this tool will remain the Steam Deck, for exactly the reason you mention. There's very little in the world of Linux that will "just work" on every system, and I don't intend to be the next person to die on that hill 😅

> Maybe it's something to consider further in the future, or just safeguard against unsupported configurations for now.

My intent is to say "this can technically work on other platforms, but I make no guarantees and fixes will be best-effort/low priority. I haven't released a public statement about it just yet, but I plan to soon.

> Launcher.sh sets incorrect scale (would research more to figure out why this happens on my system specifically)

#93 is open for that right now, and should be merged soon! This is an issue with the GUI framework used, it hates scaling and you HAVE to set it at runtime for odd resolutions.

> Swappiness value doesn't persist on Pop!_OS

Yeah, this one is going to be difficult to do, even if I wanted to. Removing arbitrary tunings from other OSs is basically asking for trouble, especially system units.

> Swapfiles supported but swap partitions are not

This was at my request, I'd really rather not get into the same space as something like GParted, or risk data loss.

> VRAM instructions are irrelevant for non-Deck devices

This is a good end-cap to enforce that I'll still be focusing on the Deck for the foreseeable future. It's possible that I might build it out to more operating systems in the future, but it'll be on a "whitelist" basis, rather than a "works on every machine" basis.

As a final note on this, all of the tweaks that CU2 currently does are "simple" to implement for most Linux users, so the cost/value proposition of this tool isn't nearly as high in those cases in my opinion. The tool was made for the Deck on account of it being a much more mainstream device, with much less experienced users on the whole.

Hopefully this all made sense! Thank you for the very detailed comment and for tracking down what was happening in your case.

**Comment by brandonbeaumia** [comment] 2023-03-03 20:41
Yes, a very well-considered position and I understand completely, especially as a side project I can tell you've put a TON of work into this and expanding to general availability would be a huge task.

I think a lot of the value of the project is the deep knowledge and testing of the tweaks. Plus you're right about the tweaks being relatively simple to implement, but I had a heck of a time Googling around for how to get some of these things changed on my own system (even after reading through the code a bit). Maybe an easier way to make this available for all systems would be a wiki page documenting the commands that CU uses behind the scenes (potentially including caveats on a per-distro basis). Then instead of saying "try it if you want" you can say "DON'T try it: follow this wiki page instead".

**Comment by CryoByte33** [comment] 2023-03-03 20:43
> Maybe an easier way to make this available for all systems would be a wiki page documenting the commands that CU uses behind the scenes

Check out docs/tweak-explanations.md in the repo here 😉

**Comment by brandonbeaumia** [comment] 2023-03-03 20:51
> Check out docs/tweak-explanation.md in the repo here wink

Oh my. Well I would've used this from the start if I had read the homepage carefully enough! 🤦 Thank you so much.

**Comment by CryoByte33** [comment] 2023-03-08 19:58
I've updated the README to reflect the direction of the tool so I'll be closing this, but if anyone still has an issue with general Linux support, feel free to open another!

**Closed by CryoByte33** 2023-03-08 19:58 UTC
Labels: enhancement
